/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "future": {
    "v4": {
      "removeLegacyPostBuildHeadAttribute": false,
      "useCssCascadeLayers": false
    },
    "experimental_faster": {
      "swcJsLoader": false,
      "swcJsMinimizer": false,
      "swcHtmlMinimizer": false,
      "lightningCssMinimizer": false,
      "mdxCrossCompilerCache": false,
      "rspackBundler": false,
      "rspackPersistentCache": false,
      "ssgWorkerThreads": false
    },
    "experimental_storage": {
      "type": "localStorage",
      "namespace": false
    },
    "experimental_router": "browser"
  },
  "title": "QwkSearch",
  "url": "https://qwksearch.com",
  "baseUrl": "/docs/",
  "onBrokenLinks": "ignore",
  "onBrokenMarkdownLinks": "ignore",
  "favicon": "https://qwksearch.com/favicon.ico",
  "projectName": "QwkSearch",
  "presets": [
    [
      "classic",
      {
        "docs": {
          "path": "src",
          "routeBasePath": "/",
          "editUrl": "https://github.com/vtempest/ai-research-agent/tree/master/apps/docs/",
          "sidebarPath": "./config/sidebars.ts",
          "docItemComponent": "@theme/ApiItem"
        },
        "blog": false,
        "theme": {
          "customCss": "./config/docs-theme-beige.css"
        },
        "gtag": {
          "trackingID": "G-E5TZ32BZD",
          "anonymizeIP": false
        }
      }
    ]
  ],
  "plugins": [
    [
      "docusaurus-plugin-openapi-docs",
      {
        "id": "openapi",
        "docsPluginId": "classic",
        "config": {
          "apispec": {
            "specPath": "./openapi-docs.yml",
            "outputDir": "./src/api",
            "sidebarOptions": {
              "groupPathsBy": "tag",
              "categoryLinkSource": "info",
              "sidebarCollapsed": false
            },
            "infoTemplate": "config/info.mustache",
            "tagTemplate": "config/tag.mustache",
            "schemaTemplate": "config/schema.mustache",
            "template": "./config/openapi.mustache",
            "hideSendButton": true,
            "markdownGenerators": {},
            "showSchemas": false
          }
        }
      }
    ],
    "/mnt/data/Projects/ai-research-agent/node_modules/docusaurus-lunr-search/src/index.js",
    [
      "docusaurus-plugin-typedoc",
      {
        "id": "web",
        "entryPoints": [
          "../web/src/lib/**/*"
        ],
        "exclude": [
          "**/node_modules/**/*",
          "**/components/ui/**/*",
          "pages/**/*"
        ],
        "tsconfig": "../web/tsconfig.json",
        "out": "./src/web",
        "readme": "../../readme.md",
        "sourceLinkTemplate": "https://github.com/vtempest/ai-research-agent/tree/master/{path}#L{line}",
        "disableSources": false,
        "sidebar": {
          "pretty": true
        },
        "textContentMappings": {
          "title.indexPage": "QwkSearch API",
          "title.memberPage": "{name}"
        },
        "parametersFormat": "htmlTable",
        "indexFormat": "list",
        "expandParameters": true,
        "interfacePropertiesFormat": "htmlTable",
        "propertyMembersFormat": "htmlTable",
        "enumMembersFormat": "htmlTable",
        "typeDeclarationFormat": "htmlTable",
        "typeDeclarationVisibility": "compact",
        "sanitizeComments": false,
        "useHTMLEncodedBrackets": true,
        "hideBreadcrumbs": false,
        "hideGroupHeadings": true,
        "hidePageHeader": true,
        "hidePageTitle": true,
        "outputFileStrategy": "modules",
        "useCodeBlocks": true
      }
    ],
    [
      "docusaurus-plugin-typedoc",
      {
        "id": "functions",
        "entryPoints": [
          "../../packages/ai-research-agent/src/**/*"
        ],
        "exclude": [
          "**/node_modules/**/*",
          "**/components/ui/**/*",
          "pages/**/*"
        ],
        "tsconfig": "../../packages/ai-research-agent/tsconfig.json",
        "out": "./src/functions",
        "readme": "../../readme.md",
        "sourceLinkTemplate": "https://github.com/vtempest/ai-research-agent/tree/master/{path}#L{line}",
        "disableSources": false,
        "sidebar": {
          "pretty": true
        },
        "textContentMappings": {
          "title.indexPage": "QwkSearch API",
          "title.memberPage": "{name}"
        },
        "parametersFormat": "htmlTable",
        "indexFormat": "list",
        "expandParameters": true,
        "interfacePropertiesFormat": "htmlTable",
        "propertyMembersFormat": "htmlTable",
        "enumMembersFormat": "htmlTable",
        "typeDeclarationFormat": "htmlTable",
        "typeDeclarationVisibility": "compact",
        "sanitizeComments": false,
        "useHTMLEncodedBrackets": true,
        "hideBreadcrumbs": false,
        "hideGroupHeadings": true,
        "hidePageHeader": true,
        "hidePageTitle": true,
        "outputFileStrategy": "modules",
        "useCodeBlocks": true
      }
    ],
    [
      "docusaurus-plugin-typedoc",
      {
        "id": "neural-net",
        "entryPoints": [
          "../../packages/neural-net/src/**/*"
        ],
        "exclude": [
          "**/node_modules/**/*",
          "**/components/ui/**/*",
          "pages/**/*"
        ],
        "tsconfig": "../../packages/neural-net/tsconfig.json",
        "out": "./src/neural-net",
        "readme": "../../readme.md",
        "sourceLinkTemplate": "https://github.com/vtempest/ai-research-agent/tree/master/{path}#L{line}",
        "disableSources": false,
        "sidebar": {
          "pretty": true
        },
        "textContentMappings": {
          "title.indexPage": "QwkSearch API",
          "title.memberPage": "{name}"
        },
        "parametersFormat": "htmlTable",
        "indexFormat": "list",
        "expandParameters": true,
        "interfacePropertiesFormat": "htmlTable",
        "propertyMembersFormat": "htmlTable",
        "enumMembersFormat": "htmlTable",
        "typeDeclarationFormat": "htmlTable",
        "typeDeclarationVisibility": "compact",
        "sanitizeComments": false,
        "useHTMLEncodedBrackets": true,
        "hideBreadcrumbs": false,
        "hideGroupHeadings": true,
        "hidePageHeader": true,
        "hidePageTitle": true,
        "outputFileStrategy": "modules",
        "useCodeBlocks": true
      }
    ]
  ],
  "themeConfig": {
    "src": {
      "sidebar": {
        "hideable": true
      }
    },
    "navbar": {
      "title": "QwkSearch Docs",
      "logo": {
        "alt": "logo",
        "src": "https://qwksearch.com/icons/app-icon.svg",
        "href": "/"
      },
      "items": [
        {
          "to": "/web",
          "label": "👋 Overview",
          "position": "left"
        },
        {
          "to": "/category/qwksearch-api",
          "label": "🔌 API Routes",
          "position": "left"
        },
        {
          "to": "/functions/modules",
          "label": "🔧 Core Functions",
          "position": "left"
        },
        {
          "to": "/web/modules",
          "label": "💻 Web App",
          "position": "left"
        },
        {
          "to": "https://qwksearch.com/",
          "label": "🚀 Demo",
          "position": "right"
        }
      ],
      "hideOnScroll": false
    },
    "languageTabs": [
      {
        "highlight": "javascript",
        "language": "nodejs",
        "logoClass": "nodejs"
      },
      {
        "highlight": "javascript",
        "language": "javascript",
        "logoClass": "javascript"
      },
      {
        "highlight": "python",
        "language": "python",
        "logoClass": "python"
      },
      {
        "highlight": "bash",
        "language": "curl",
        "logoClass": "curl"
      },
      {
        "highlight": "powershell",
        "language": "powershell",
        "logoClass": "powershell"
      },
      {
        "highlight": "rust",
        "language": "rust",
        "logoClass": "rust"
      },
      {
        "highlight": "c",
        "language": "c",
        "logoClass": "c"
      },
      {
        "highlight": "swift",
        "language": "swift",
        "logoClass": "swift"
      },
      {
        "highlight": "kotlin",
        "language": "kotlin",
        "logoClass": "kotlin"
      },
      {
        "highlight": "java",
        "language": "java",
        "logoClass": "java"
      },
      {
        "highlight": "php",
        "language": "php",
        "logoClass": "php"
      }
    ],
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    },
    "metadata": [],
    "prism": {
      "additionalLanguages": [],
      "theme": {
        "plain": {
          "color": "#bfc7d5",
          "backgroundColor": "#292d3e"
        },
        "styles": [
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(105, 112, 152)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "string",
              "inserted"
            ],
            "style": {
              "color": "rgb(195, 232, 141)"
            }
          },
          {
            "types": [
              "number"
            ],
            "style": {
              "color": "rgb(247, 140, 108)"
            }
          },
          {
            "types": [
              "builtin",
              "char",
              "constant",
              "function"
            ],
            "style": {
              "color": "rgb(130, 170, 255)"
            }
          },
          {
            "types": [
              "punctuation",
              "selector"
            ],
            "style": {
              "color": "rgb(199, 146, 234)"
            }
          },
          {
            "types": [
              "variable"
            ],
            "style": {
              "color": "rgb(191, 199, 213)"
            }
          },
          {
            "types": [
              "class-name",
              "attr-name"
            ],
            "style": {
              "color": "rgb(255, 203, 107)"
            }
          },
          {
            "types": [
              "tag",
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 114)"
            }
          },
          {
            "types": [
              "operator"
            ],
            "style": {
              "color": "rgb(137, 221, 255)"
            }
          },
          {
            "types": [
              "boolean"
            ],
            "style": {
              "color": "rgb(255, 88, 116)"
            }
          },
          {
            "types": [
              "keyword"
            ],
            "style": {
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "doctype"
            ],
            "style": {
              "color": "rgb(199, 146, 234)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "color": "rgb(178, 204, 214)"
            }
          },
          {
            "types": [
              "url"
            ],
            "style": {
              "color": "rgb(221, 221, 221)"
            }
          }
        ]
      },
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "themes": [
    "docusaurus-theme-openapi-docs"
  ],
  "stylesheets": [
    {
      "href": "https://use.fontawesome.com/releases/v5.11.0/css/all.css",
      "type": "text/css"
    }
  ],
  "baseUrlIssueBanner": true,
  "i18n": {
    "defaultLocale": "en",
    "path": "i18n",
    "locales": [
      "en"
    ],
    "localeConfigs": {}
  },
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "scripts": [],
  "headTags": [],
  "clientModules": [],
  "tagline": "",
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "format": "mdx",
    "mermaid": false,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    }
  }
};
