// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://qwksearch.com/api' | (string & {});
};

export type ErrorResponse = {
    error?: string;
    message?: string;
};

export type ModelWithProvider = {
    providerId: string;
    key: string;
};

export type SearchResult = {
    title?: string;
    url?: string;
    content?: string;
    img_src?: string;
    engine?: string;
    parsed_url?: Array<string>;
};

export type DomainSuggestion = {
    domain?: string;
    name?: string;
    favicon?: string;
    rank?: number;
};

export type Article = {
    url?: string;
    title?: string;
    cite?: string;
    author?: string;
    author_cite?: string;
    author_short?: string;
    author_type?: string;
    date?: string;
    source?: string;
    word_count?: number;
    html?: string;
    followUpQuestions?: Array<string>;
    qaHistory?: Array<{
        question?: string;
        answer?: string;
    }>;
};

export type Chat = {
    id?: string;
    title?: string;
    createdAt?: string;
    focusMode?: string;
    userId?: string;
    files?: Array<string>;
    messageCount?: number;
};

export type Favorite = {
    id?: number;
    userId?: string;
    url?: string;
    title?: string;
    cite?: string;
    author?: string;
    author_cite?: string;
    date?: string;
    source?: string;
    word_count?: number;
    html?: string;
    createdAt?: string;
};

export type Document = {
    id?: number;
    title?: string;
    name?: string;
    content?: string;
    parentId?: number;
    isFolder?: boolean;
    isExpanded?: boolean;
    metadata?: {
        [key: string]: unknown;
    };
    tags?: Array<string>;
    userId?: string;
    createdAt?: string;
    updatedAt?: string;
};

export type Quote = {
    id: string;
    documentId: string;
    text: string;
    source?: string;
    author?: string;
    url?: string;
    pageNumber?: number;
    tags?: Array<string>;
    createdAt?: string;
};

export type Provider = {
    id?: string;
    type?: string;
    name?: string;
    config?: {
        [key: string]: unknown;
    };
    models?: Array<{
        [key: string]: unknown;
    }>;
};

export type McpServer = {
    id?: string;
    type?: string;
    name?: string;
    config?: {
        [key: string]: unknown;
    };
    enabled?: boolean;
};

export type Notebook = {
    id?: string;
    title?: string;
    createdAt?: string;
};

export type NotebookSource = {
    id?: string;
    title?: string;
    url?: string;
};

export type UploadedFile = {
    fileName?: string;
    fileExtension?: string;
    fileId?: string;
    sizeBytes?: number;
};

export type UserProfile = {
    id?: string;
    name?: string;
    email?: string;
    image?: string;
    apiKey?: string;
    createdAt?: string;
};

export type UserSession = {
    id?: string;
    token?: string;
    ipAddress?: string;
    userAgent?: string;
    createdAt?: string;
    expiresAt?: string;
    isCurrent?: boolean;
};

export type StorageInfo = {
    used?: number;
    quota?: number;
    remaining?: number;
    allowed?: boolean;
    usedMB?: number;
    quotaMB?: number;
    remainingMB?: number;
    percentage?: number;
};

export type ArticleFollowupsData = {
    body: {
        article: string;
        chatHistory?: Array<{
            role?: string;
            content?: string;
        }>;
        maxQuestions?: number;
        provider?: string;
        chatModel?: ModelWithProvider;
    };
    path?: never;
    query?: never;
    url: '/agent/article-followups';
};

export type ArticleFollowupsErrors = {
    /**
     * Internal server error
     */
    500: ErrorResponse;
};

export type ArticleFollowupsError = ArticleFollowupsErrors[keyof ArticleFollowupsErrors];

export type ArticleFollowupsResponses = {
    /**
     * Follow-up questions
     */
    200: {
        extract?: Array<string>;
        success?: boolean;
    };
};

export type ArticleFollowupsResponse = ArticleFollowupsResponses[keyof ArticleFollowupsResponses];

export type ArticleQaData = {
    body: {
        article: string;
        question: string;
        chatHistory?: Array<{
            role?: string;
            content?: string;
        }>;
        provider?: string;
        chatModel?: ModelWithProvider;
    };
    path?: never;
    query?: never;
    url: '/agent/article-qa';
};

export type ArticleQaErrors = {
    /**
     * Internal server error
     */
    500: ErrorResponse;
};

export type ArticleQaError = ArticleQaErrors[keyof ArticleQaErrors];

export type ArticleQaResponses = {
    /**
     * Answer
     */
    200: {
        content?: string;
        success?: boolean;
    };
};

export type ArticleQaResponse = ArticleQaResponses[keyof ArticleQaResponses];

export type AutocompleteData = {
    body?: never;
    path?: never;
    query: {
        q: string;
        locale?: string;
        /**
         * Comma-separated: google, ddg, wikipedia
         */
        backends?: string;
        limit?: number;
    };
    url: '/agent/autocomplete';
};

export type AutocompleteResponses = {
    /**
     * Autocomplete results
     */
    200: {
        suggestions?: Array<string>;
        domains?: Array<DomainSuggestion>;
    };
};

export type AutocompleteResponse = AutocompleteResponses[keyof AutocompleteResponses];

export type AgentChatData = {
    body: {
        message: {
            messageId: string;
            chatId: string;
            content: string;
        };
        optimizationMode: 'speed' | 'balanced' | 'quality';
        focusMode: string;
        category?: string;
        history?: Array<[
            string,
            string
        ]>;
        files?: Array<string>;
        chatModel: ModelWithProvider;
        sourceExtractionEnabled?: boolean;
        thinkingTimeLimit?: number;
        systemInstructions?: string;
        queryExpansionPrompt?: string;
    };
    path?: never;
    query?: never;
    url: '/agent/chat';
};

export type AgentChatErrors = {
    /**
     * Bad request
     */
    400: ErrorResponse;
    /**
     * Internal server error
     */
    500: ErrorResponse;
};

export type AgentChatError = AgentChatErrors[keyof AgentChatErrors];

export type AgentChatResponses = {
    /**
     * Server-sent events stream
     */
    200: string;
};

export type AgentChatResponse = AgentChatResponses[keyof AgentChatResponses];

export type DeleteAllChatsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/agent/chats';
};

export type DeleteAllChatsErrors = {
    /**
     * Authentication required
     */
    401: ErrorResponse;
};

export type DeleteAllChatsError = DeleteAllChatsErrors[keyof DeleteAllChatsErrors];

export type DeleteAllChatsResponses = {
    /**
     * All chats deleted
     */
    200: {
        message?: string;
    };
};

export type DeleteAllChatsResponse = DeleteAllChatsResponses[keyof DeleteAllChatsResponses];

export type ListChatsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/agent/chats';
};

export type ListChatsErrors = {
    /**
     * Authentication required
     */
    401: ErrorResponse;
};

export type ListChatsError = ListChatsErrors[keyof ListChatsErrors];

export type ListChatsResponses = {
    /**
     * Chat list
     */
    200: {
        chats?: Array<Chat>;
    };
};

export type ListChatsResponse = ListChatsResponses[keyof ListChatsResponses];

export type SearchChatsData = {
    body?: never;
    path?: never;
    query: {
        q: string;
    };
    url: '/agent/chats/search';
};

export type SearchChatsErrors = {
    /**
     * Authentication required
     */
    401: ErrorResponse;
};

export type SearchChatsError = SearchChatsErrors[keyof SearchChatsErrors];

export type SearchChatsResponses = {
    /**
     * Matching chats
     */
    200: {
        chats?: Array<Chat>;
    };
};

export type SearchChatsResponse = SearchChatsResponses[keyof SearchChatsResponses];

export type ShareChatData = {
    body: {
        chatId: string;
    };
    path?: never;
    query?: never;
    url: '/agent/chats/share';
};

export type ShareChatErrors = {
    /**
     * Authentication required
     */
    401: ErrorResponse;
};

export type ShareChatError = ShareChatErrors[keyof ShareChatErrors];

export type ShareChatResponses = {
    /**
     * Share URL
     */
    200: {
        success?: boolean;
        data?: {
            chatId?: string;
            shareUrl?: string;
        };
    };
};

export type ShareChatResponse = ShareChatResponses[keyof ShareChatResponses];

export type DeleteChatByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/agent/chats/{id}';
};

export type DeleteChatByIdErrors = {
    /**
     * Authentication required
     */
    401: ErrorResponse;
    /**
     * Not found
     */
    404: ErrorResponse;
};

export type DeleteChatByIdError = DeleteChatByIdErrors[keyof DeleteChatByIdErrors];

export type DeleteChatByIdResponses = {
    /**
     * Deleted
     */
    200: {
        message?: string;
    };
};

export type DeleteChatByIdResponse = DeleteChatByIdResponses[keyof DeleteChatByIdResponses];

export type GetChatByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/agent/chats/{id}';
};

export type GetChatByIdErrors = {
    /**
     * Not found
     */
    404: ErrorResponse;
};

export type GetChatByIdError = GetChatByIdErrors[keyof GetChatByIdErrors];

export type GetChatByIdResponses = {
    /**
     * Chat and messages
     */
    200: {
        chat?: Chat;
        messages?: Array<{
            [key: string]: unknown;
        }>;
    };
};

export type GetChatByIdResponse = GetChatByIdResponses[keyof GetChatByIdResponses];

export type DiscoverContentData = {
    body?: never;
    path?: never;
    query?: {
        topic?: 'tech' | 'finance' | 'art' | 'sports' | 'entertainment';
        mode?: 'normal' | 'preview';
    };
    url: '/agent/discover';
};

export type DiscoverContentErrors = {
    /**
     * Internal server error
     */
    500: ErrorResponse;
};

export type DiscoverContentError = DiscoverContentErrors[keyof DiscoverContentErrors];

export type DiscoverContentResponses = {
    /**
     * Discovered content
     */
    200: {
        blogs?: Array<SearchResult>;
    };
};

export type DiscoverContentResponse = DiscoverContentResponses[keyof DiscoverContentResponses];

export type SaveMessageData = {
    body: {
        chatId: string;
        messageId: string;
        role: 'user' | 'assistant';
        content?: string;
        suggestions?: Array<string>;
        sources?: Array<{
            [key: string]: unknown;
        }>;
    };
    path?: never;
    query?: never;
    url: '/agent/messages';
};

export type SaveMessageErrors = {
    /**
     * Authentication required
     */
    401: ErrorResponse;
};

export type SaveMessageError = SaveMessageErrors[keyof SaveMessageErrors];

export type SaveMessageResponses = {
    /**
     * Saved
     */
    200: {
        message?: string;
    };
};

export type SaveMessageResponse = SaveMessageResponses[keyof SaveMessageResponses];

export type RewriteTextData = {
    body: {
        text: string;
        prompt?: string;
    };
    path?: never;
    query?: never;
    url: '/agent/rewrite';
};

export type RewriteTextErrors = {
    /**
     * Internal server error
     */
    500: ErrorResponse;
};

export type RewriteTextError = RewriteTextErrors[keyof RewriteTextErrors];

export type RewriteTextResponses = {
    /**
     * Rewritten text
     */
    200: {
        rewrittenText?: string;
    };
};

export type RewriteTextResponse = RewriteTextResponses[keyof RewriteTextResponses];

export type AgentSearchData = {
    body?: never;
    path?: never;
    query: {
        q: string;
        cat?: 'general' | 'news' | 'images' | 'videos' | 'it' | 'science';
        page?: number;
        lang?: string;
        safesearch?: boolean;
        recency?: 'day' | 'week' | 'month' | 'year';
        publicInstances?: boolean;
    };
    url: '/agent/search';
};

export type AgentSearchErrors = {
    /**
     * Bad request
     */
    400: ErrorResponse;
};

export type AgentSearchError = AgentSearchErrors[keyof AgentSearchErrors];

export type AgentSearchResponses = {
    /**
     * Search results
     */
    200: {
        results?: Array<SearchResult>;
        suggestions?: Array<string>;
        elapsedTime?: number;
    };
};

export type AgentSearchResponse = AgentSearchResponses[keyof AgentSearchResponses];

export type GenerateSuggestionsData = {
    body: {
        chatHistory: Array<{
            [key: string]: unknown;
        }>;
        chatModel: ModelWithProvider;
        maxQuestions?: number;
        promptTemplate?: string;
    };
    path?: never;
    query?: never;
    url: '/agent/suggestions';
};

export type GenerateSuggestionsErrors = {
    /**
     * Internal server error
     */
    500: ErrorResponse;
};

export type GenerateSuggestionsError = GenerateSuggestionsErrors[keyof GenerateSuggestionsErrors];

export type GenerateSuggestionsResponses = {
    /**
     * Suggestions
     */
    200: {
        suggestions?: Array<string>;
    };
};

export type GenerateSuggestionsResponse = GenerateSuggestionsResponses[keyof GenerateSuggestionsResponses];

export type TestModelsData = {
    body: {
        providerType: string;
        apiKey: string;
        onlyFree?: boolean;
    };
    path?: never;
    query?: never;
    url: '/agent/test-models';
};

export type TestModelsResponses = {
    /**
     * Test results
     */
    200: {
        [key: string]: unknown;
    };
};

export type TestModelsResponse = TestModelsResponses[keyof TestModelsResponses];

export type TranscribeAudioData = {
    body: {
        file: Blob | File;
        model?: 'small' | 'fast' | 'medium' | 'turbo' | 'large';
    };
    path?: never;
    query?: never;
    url: '/agent/transcript';
};

export type TranscribeAudioResponses = {
    /**
     * Transcript
     */
    200: {
        text?: string;
        model?: string;
    };
};

export type TranscribeAudioResponse = TranscribeAudioResponses[keyof TranscribeAudioResponses];

export type TextToSpeechData = {
    body: {
        text: string;
        voice?: string;
        provider?: 'kokoro' | 'deepgram';
    };
    path?: never;
    query?: never;
    url: '/agent/voice';
};

export type TextToSpeechErrors = {
    /**
     * Rate limit exceeded
     */
    429: {
        error?: string;
        rateLimited?: boolean;
    };
};

export type TextToSpeechError = TextToSpeechErrors[keyof TextToSpeechErrors];

export type TextToSpeechResponses = {
    /**
     * Audio binary
     */
    200: Blob | File;
};

export type TextToSpeechResponse = TextToSpeechResponses[keyof TextToSpeechResponses];

export type GetConfigData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/config';
};

export type GetConfigResponses = {
    /**
     * Config values and UI field definitions
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetConfigResponse = GetConfigResponses[keyof GetConfigResponses];

export type SaveConfigData = {
    body: {
        key: string;
        value: string;
    };
    path?: never;
    query?: never;
    url: '/config';
};

export type SaveConfigResponses = {
    /**
     * Saved
     */
    200: {
        message?: string;
    };
};

export type SaveConfigResponse = SaveConfigResponses[keyof SaveConfigResponses];

export type GetArticleData = {
    body?: never;
    path?: never;
    query: {
        url: string;
    };
    url: '/doc/article';
};

export type GetArticleErrors = {
    /**
     * Bad request
     */
    400: ErrorResponse;
    /**
     * Internal server error
     */
    500: ErrorResponse;
};

export type GetArticleError = GetArticleErrors[keyof GetArticleErrors];

export type GetArticleResponses = {
    /**
     * Article content
     */
    200: {
        cached?: boolean;
        article?: Article;
        isVideo?: boolean;
    };
};

export type GetArticleResponse = GetArticleResponses[keyof GetArticleResponses];

export type UpdateArticleData = {
    body: {
        url: string;
        question?: string;
        answer?: string;
        followUpQuestions?: Array<string>;
    };
    path?: never;
    query?: never;
    url: '/doc/article';
};

export type UpdateArticleErrors = {
    /**
     * Bad request
     */
    400: ErrorResponse;
};

export type UpdateArticleError = UpdateArticleErrors[keyof UpdateArticleErrors];

export type UpdateArticleResponses = {
    /**
     * Stored
     */
    200: {
        success?: boolean;
    };
};

export type UpdateArticleResponse = UpdateArticleResponses[keyof UpdateArticleResponses];

export type ListDocumentsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/doc/documents';
};

export type ListDocumentsResponses = {
    /**
     * Document list
     */
    200: Array<Document>;
};

export type ListDocumentsResponse = ListDocumentsResponses[keyof ListDocumentsResponses];

export type CreateDocumentData = {
    body: {
        name?: string;
        title?: string;
        content?: string;
        parentId?: number;
        isFolder?: boolean;
        metadata?: {
            [key: string]: unknown;
        };
        tags?: Array<string>;
    };
    path?: never;
    query?: never;
    url: '/doc/documents';
};

export type CreateDocumentResponses = {
    /**
     * Created document
     */
    201: Document;
};

export type CreateDocumentResponse = CreateDocumentResponses[keyof CreateDocumentResponses];

export type DeleteDocumentData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/doc/documents/{id}';
};

export type DeleteDocumentErrors = {
    /**
     * Not found
     */
    404: ErrorResponse;
};

export type DeleteDocumentError = DeleteDocumentErrors[keyof DeleteDocumentErrors];

export type DeleteDocumentResponses = {
    /**
     * Deleted
     */
    200: {
        success?: boolean;
    };
};

export type DeleteDocumentResponse = DeleteDocumentResponses[keyof DeleteDocumentResponses];

export type GetDocumentByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/doc/documents/{id}';
};

export type GetDocumentByIdErrors = {
    /**
     * Not found
     */
    404: ErrorResponse;
};

export type GetDocumentByIdError = GetDocumentByIdErrors[keyof GetDocumentByIdErrors];

export type GetDocumentByIdResponses = {
    /**
     * Document
     */
    200: Document;
};

export type GetDocumentByIdResponse = GetDocumentByIdResponses[keyof GetDocumentByIdResponses];

export type UpdateDocumentData = {
    body: {
        title?: string;
        content?: string;
        parentId?: number;
        isExpanded?: boolean;
        metadata?: {
            [key: string]: unknown;
        };
        name?: string;
    };
    path: {
        id: number;
    };
    query?: never;
    url: '/doc/documents/{id}';
};

export type UpdateDocumentErrors = {
    /**
     * Not found
     */
    404: ErrorResponse;
};

export type UpdateDocumentError = UpdateDocumentErrors[keyof UpdateDocumentErrors];

export type UpdateDocumentResponses = {
    /**
     * Updated document
     */
    200: Document;
};

export type UpdateDocumentResponse = UpdateDocumentResponses[keyof UpdateDocumentResponses];

export type RemoveFavoriteData = {
    body?: never;
    path?: never;
    query: {
        url: string;
    };
    url: '/doc/favorites';
};

export type RemoveFavoriteErrors = {
    /**
     * Authentication required
     */
    401: ErrorResponse;
};

export type RemoveFavoriteError = RemoveFavoriteErrors[keyof RemoveFavoriteErrors];

export type RemoveFavoriteResponses = {
    /**
     * Removed
     */
    200: {
        message?: string;
    };
};

export type RemoveFavoriteResponse = RemoveFavoriteResponses[keyof RemoveFavoriteResponses];

export type ListFavoritesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/doc/favorites';
};

export type ListFavoritesErrors = {
    /**
     * Authentication required
     */
    401: ErrorResponse;
};

export type ListFavoritesError = ListFavoritesErrors[keyof ListFavoritesErrors];

export type ListFavoritesResponses = {
    /**
     * Favorites
     */
    200: {
        favorites?: Array<Favorite>;
    };
};

export type ListFavoritesResponse = ListFavoritesResponses[keyof ListFavoritesResponses];

export type AddFavoriteData = {
    body: {
        url: string;
        title?: string;
        cite?: string;
        author?: string;
        author_cite?: string;
        date?: string;
        source?: string;
        word_count?: number;
        html?: string;
    };
    path?: never;
    query?: never;
    url: '/doc/favorites';
};

export type AddFavoriteErrors = {
    /**
     * Authentication required
     */
    401: ErrorResponse;
};

export type AddFavoriteError = AddFavoriteErrors[keyof AddFavoriteErrors];

export type AddFavoriteResponses = {
    /**
     * Already favorited
     */
    200: {
        message?: string;
        favorite?: Favorite;
    };
    /**
     * Created
     */
    201: {
        message?: string;
        favorite?: Favorite;
    };
};

export type AddFavoriteResponse = AddFavoriteResponses[keyof AddFavoriteResponses];

export type GoogleDocsAuthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/doc/google-docs/auth';
};

export type GoogleDocsAuthResponses = {
    /**
     * Auth URL
     */
    200: {
        success?: boolean;
        data?: {
            authUrl?: string;
        };
    };
};

export type GoogleDocsAuthResponse = GoogleDocsAuthResponses[keyof GoogleDocsAuthResponses];

export type GoogleDocsAuthStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/doc/google-docs/auth/status';
};

export type GoogleDocsAuthStatusResponses = {
    /**
     * Connection status
     */
    200: {
        success?: boolean;
        isConnected?: boolean;
        hasAccessToken?: boolean;
        hasRefreshToken?: boolean;
    };
};

export type GoogleDocsAuthStatusResponse = GoogleDocsAuthStatusResponses[keyof GoogleDocsAuthStatusResponses];

export type GoogleDocsCallbackData = {
    body?: never;
    path?: never;
    query: {
        code: string;
    };
    url: '/doc/google-docs/callback';
};

export type GoogleDocsCallbackResponses = {
    /**
     * HTML popup-close page
     */
    200: string;
};

export type GoogleDocsCallbackResponse = GoogleDocsCallbackResponses[keyof GoogleDocsCallbackResponses];

export type ExportToGoogleDocsData = {
    body: {
        documentId: string;
        accessToken: string;
        refreshToken?: string;
    };
    path?: never;
    query?: never;
    url: '/doc/google-docs/export';
};

export type ExportToGoogleDocsResponses = {
    /**
     * Export result
     */
    200: {
        [key: string]: unknown;
    };
};

export type ExportToGoogleDocsResponse = ExportToGoogleDocsResponses[keyof ExportToGoogleDocsResponses];

export type GetGoogleDriveFileData = {
    body?: never;
    path?: never;
    query: {
        fileId: string;
    };
    url: '/doc/google-docs/files';
};

export type GetGoogleDriveFileResponses = {
    /**
     * File content (base64)
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetGoogleDriveFileResponse = GetGoogleDriveFileResponses[keyof GetGoogleDriveFileResponses];

export type ImportFromGoogleDocsData = {
    body: {
        googleDocId: string;
        accessToken: string;
        refreshToken?: string;
        parentId?: string;
    };
    path?: never;
    query?: never;
    url: '/doc/google-docs/import';
};

export type ImportFromGoogleDocsResponses = {
    /**
     * Imported
     */
    201: {
        success?: boolean;
    };
};

export type ImportFromGoogleDocsResponse = ImportFromGoogleDocsResponses[keyof ImportFromGoogleDocsResponses];

export type RefreshGoogleTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/doc/google-docs/refresh-token';
};

export type RefreshGoogleTokenResponses = {
    /**
     * Refresh result
     */
    200: {
        success?: boolean;
        message?: string;
        expiresAt?: string;
        error?: string;
        needsReauth?: boolean;
    };
};

export type RefreshGoogleTokenResponse = RefreshGoogleTokenResponses[keyof RefreshGoogleTokenResponses];

export type ShareGoogleDocData = {
    body: {
        googleDocId: string;
        accessToken: string;
        refreshToken?: string;
        emailAddress?: string;
        role?: 'reader' | 'commenter' | 'writer';
        publicLink?: boolean;
    };
    path?: never;
    query?: never;
    url: '/doc/google-docs/share';
};

export type ShareGoogleDocResponses = {
    /**
     * Share result
     */
    200: {
        [key: string]: unknown;
    };
};

export type ShareGoogleDocResponse = ShareGoogleDocResponses[keyof ShareGoogleDocResponses];

export type GetGoogleTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/doc/google-docs/token';
};

export type GetGoogleTokenResponses = {
    /**
     * Access token
     */
    200: {
        success?: boolean;
        accessToken?: string;
    };
};

export type GetGoogleTokenResponse = GetGoogleTokenResponses[keyof GetGoogleTokenResponses];

export type ListQuotesData = {
    body?: never;
    path?: never;
    query: {
        documentId: string;
    };
    url: '/doc/quotes';
};

export type ListQuotesErrors = {
    /**
     * Bad request
     */
    400: ErrorResponse;
};

export type ListQuotesError = ListQuotesErrors[keyof ListQuotesErrors];

export type ListQuotesResponses = {
    /**
     * Quotes
     */
    200: {
        success?: boolean;
        data?: Array<Quote>;
    };
};

export type ListQuotesResponse = ListQuotesResponses[keyof ListQuotesResponses];

export type CreateQuoteData = {
    body: {
        documentId: string;
        text: string;
        source?: string;
        author?: string;
        url?: string;
        pageNumber?: number;
        tags?: Array<string>;
    };
    path?: never;
    query?: never;
    url: '/doc/quotes';
};

export type CreateQuoteResponses = {
    /**
     * Created
     */
    201: {
        success?: boolean;
        data?: Quote;
    };
};

export type CreateQuoteResponse = CreateQuoteResponses[keyof CreateQuoteResponses];

export type DeleteQuoteData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/doc/quotes/{id}';
};

export type DeleteQuoteResponses = {
    /**
     * Deleted
     */
    200: {
        success?: boolean;
        data?: {
            id?: string;
        };
    };
};

export type DeleteQuoteResponse = DeleteQuoteResponses[keyof DeleteQuoteResponses];

export type UpdateQuoteData = {
    body: {
        text: string;
        source?: string;
        author?: string;
        url?: string;
        pageNumber?: number;
        tags?: Array<string>;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/doc/quotes/{id}';
};

export type UpdateQuoteResponses = {
    /**
     * Updated
     */
    200: {
        success?: boolean;
        data?: Quote;
    };
};

export type UpdateQuoteResponse = UpdateQuoteResponses[keyof UpdateQuoteResponses];

export type ShareDocumentData = {
    body: {
        documentId: string;
    };
    path?: never;
    query?: never;
    url: '/doc/share';
};

export type ShareDocumentResponses = {
    /**
     * Share info
     */
    200: {
        success?: boolean;
        data?: {
            shareId?: string;
            shareUrl?: string;
        };
    };
};

export type ShareDocumentResponse = ShareDocumentResponses[keyof ShareDocumentResponses];

export type GetSharedDocumentData = {
    body?: never;
    path: {
        /**
         * Share token
         */
        id: string;
    };
    query?: never;
    url: '/doc/share/{id}';
};

export type GetSharedDocumentErrors = {
    /**
     * Not found
     */
    404: ErrorResponse;
    /**
     * Share link expired
     */
    410: ErrorResponse;
};

export type GetSharedDocumentError = GetSharedDocumentErrors[keyof GetSharedDocumentErrors];

export type GetSharedDocumentResponses = {
    /**
     * Shared document
     */
    200: {
        success?: boolean;
        data?: Document;
    };
};

export type GetSharedDocumentResponse = GetSharedDocumentResponses[keyof GetSharedDocumentResponses];

export type DeleteUploadedFileData = {
    body?: never;
    path?: never;
    query: {
        fileId: string;
        ext?: string;
        sizeBytes?: number;
    };
    url: '/doc/uploads';
};

export type DeleteUploadedFileResponses = {
    /**
     * Deleted
     */
    200: {
        success?: boolean;
        fileId?: string;
        deleted?: Array<{
            key?: string;
            success?: boolean;
        }>;
    };
};

export type DeleteUploadedFileResponse = DeleteUploadedFileResponses[keyof DeleteUploadedFileResponses];

export type GetUploadedFileData = {
    body?: never;
    path?: never;
    query: {
        fileId: string;
    };
    url: '/doc/uploads';
};

export type GetUploadedFileResponses = {
    /**
     * File content
     */
    200: {
        title?: string;
        content?: string;
    };
};

export type GetUploadedFileResponse = GetUploadedFileResponses[keyof GetUploadedFileResponses];

export type UploadFilesData = {
    body: {
        files: Array<Blob | File>;
    };
    path?: never;
    query?: never;
    url: '/doc/uploads';
};

export type UploadFilesResponses = {
    /**
     * Uploaded files
     */
    200: {
        files?: Array<UploadedFile>;
    };
};

export type UploadFilesResponse = UploadFilesResponses[keyof UploadFilesResponses];

export type ListMcpServersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/agent/mcpservers';
};

export type ListMcpServersResponses = {
    /**
     * MCP server list
     */
    200: {
        servers?: Array<McpServer>;
    };
};

export type ListMcpServersResponse = ListMcpServersResponses[keyof ListMcpServersResponses];

export type AddMcpServerData = {
    body: {
        type: string;
        name: string;
        config: {
            [key: string]: unknown;
        };
    };
    path?: never;
    query?: never;
    url: '/agent/mcpservers';
};

export type AddMcpServerResponses = {
    /**
     * Created server
     */
    200: {
        server?: McpServer;
    };
};

export type AddMcpServerResponse = AddMcpServerResponses[keyof AddMcpServerResponses];

export type DeleteMcpServerData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/agent/mcpservers/{id}';
};

export type DeleteMcpServerResponses = {
    /**
     * Deleted
     */
    200: {
        message?: string;
    };
};

export type DeleteMcpServerResponse = DeleteMcpServerResponses[keyof DeleteMcpServerResponses];

export type UpdateMcpServerData = {
    body: {
        name?: string;
        config?: {
            [key: string]: unknown;
        };
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/agent/mcpservers/{id}';
};

export type UpdateMcpServerResponses = {
    /**
     * Updated server
     */
    200: {
        server?: McpServer;
    };
};

export type UpdateMcpServerResponse = UpdateMcpServerResponses[keyof UpdateMcpServerResponses];

export type ToggleMcpServerData = {
    body: {
        enabled: boolean;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/agent/mcpservers/{id}/toggle';
};

export type ToggleMcpServerResponses = {
    /**
     * Updated server
     */
    200: {
        server?: McpServer;
    };
};

export type ToggleMcpServerResponse = ToggleMcpServerResponses[keyof ToggleMcpServerResponses];

export type NotebooklmLoginData = {
    body: {
        email: string;
        password: string;
    };
    path?: never;
    query?: never;
    url: '/notebooklm/login';
};

export type NotebooklmLoginErrors = {
    /**
     * Authentication required
     */
    401: ErrorResponse;
};

export type NotebooklmLoginError = NotebooklmLoginErrors[keyof NotebooklmLoginErrors];

export type NotebooklmLoginResponses = {
    /**
     * Login result
     */
    200: {
        success?: boolean;
        googleEmail?: string;
        message?: string;
    };
};

export type NotebooklmLoginResponse = NotebooklmLoginResponses[keyof NotebooklmLoginResponses];

export type DisconnectNotebooklmData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/notebooklm/status';
};

export type DisconnectNotebooklmErrors = {
    /**
     * Authentication required
     */
    401: ErrorResponse;
};

export type DisconnectNotebooklmError = DisconnectNotebooklmErrors[keyof DisconnectNotebooklmErrors];

export type DisconnectNotebooklmResponses = {
    /**
     * Disconnected
     */
    200: {
        success?: boolean;
        message?: string;
    };
};

export type DisconnectNotebooklmResponse = DisconnectNotebooklmResponses[keyof DisconnectNotebooklmResponses];

export type GetNotebooklmStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/notebooklm/status';
};

export type GetNotebooklmStatusErrors = {
    /**
     * Authentication required
     */
    401: ErrorResponse;
};

export type GetNotebooklmStatusError = GetNotebooklmStatusErrors[keyof GetNotebooklmStatusErrors];

export type GetNotebooklmStatusResponses = {
    /**
     * Connection status
     */
    200: {
        connected?: boolean;
        googleEmail?: string;
        createdAt?: string;
        expiresAt?: string;
    };
};

export type GetNotebooklmStatusResponse = GetNotebooklmStatusResponses[keyof GetNotebooklmStatusResponses];

export type ListNotebooksData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/notebooklm/notebooks';
};

export type ListNotebooksErrors = {
    /**
     * Authentication required
     */
    401: ErrorResponse;
};

export type ListNotebooksError = ListNotebooksErrors[keyof ListNotebooksErrors];

export type ListNotebooksResponses = {
    /**
     * Notebooks
     */
    200: {
        notebooks?: Array<Notebook>;
    };
};

export type ListNotebooksResponse = ListNotebooksResponses[keyof ListNotebooksResponses];

export type CreateNotebookData = {
    body: {
        title: string;
    };
    path?: never;
    query?: never;
    url: '/notebooklm/notebooks';
};

export type CreateNotebookErrors = {
    /**
     * Authentication required
     */
    401: ErrorResponse;
};

export type CreateNotebookError = CreateNotebookErrors[keyof CreateNotebookErrors];

export type CreateNotebookResponses = {
    /**
     * Created notebook
     */
    201: {
        notebook?: Notebook;
    };
};

export type CreateNotebookResponse = CreateNotebookResponses[keyof CreateNotebookResponses];

export type DeleteNotebookData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/notebooklm/notebooks/{id}';
};

export type DeleteNotebookErrors = {
    /**
     * Authentication required
     */
    401: ErrorResponse;
};

export type DeleteNotebookError = DeleteNotebookErrors[keyof DeleteNotebookErrors];

export type DeleteNotebookResponses = {
    /**
     * Deleted
     */
    200: {
        success?: boolean;
    };
};

export type DeleteNotebookResponse = DeleteNotebookResponses[keyof DeleteNotebookResponses];

export type AskNotebookData = {
    body: {
        query: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/notebooklm/notebooks/{id}/ask';
};

export type AskNotebookErrors = {
    /**
     * Authentication required
     */
    401: ErrorResponse;
};

export type AskNotebookError = AskNotebookErrors[keyof AskNotebookErrors];

export type AskNotebookResponses = {
    /**
     * Answer
     */
    200: {
        [key: string]: unknown;
    };
};

export type AskNotebookResponse = AskNotebookResponses[keyof AskNotebookResponses];

export type GenerateNotebookAudioData = {
    body?: {
        instructions?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/notebooklm/notebooks/{id}/audio';
};

export type GenerateNotebookAudioErrors = {
    /**
     * Authentication required
     */
    401: ErrorResponse;
};

export type GenerateNotebookAudioError = GenerateNotebookAudioErrors[keyof GenerateNotebookAudioErrors];

export type GenerateNotebookAudioResponses = {
    /**
     * Audio result
     */
    200: {
        [key: string]: unknown;
    };
};

export type GenerateNotebookAudioResponse = GenerateNotebookAudioResponses[keyof GenerateNotebookAudioResponses];

export type ListNotebookSourcesData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/notebooklm/notebooks/{id}/sources';
};

export type ListNotebookSourcesErrors = {
    /**
     * Authentication required
     */
    401: ErrorResponse;
};

export type ListNotebookSourcesError = ListNotebookSourcesErrors[keyof ListNotebookSourcesErrors];

export type ListNotebookSourcesResponses = {
    /**
     * Sources
     */
    200: {
        sources?: Array<NotebookSource>;
    };
};

export type ListNotebookSourcesResponse = ListNotebookSourcesResponses[keyof ListNotebookSourcesResponses];

export type AddNotebookSourceData = {
    body: {
        url?: string;
        text?: string;
        title?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/notebooklm/notebooks/{id}/sources';
};

export type AddNotebookSourceErrors = {
    /**
     * Authentication required
     */
    401: ErrorResponse;
};

export type AddNotebookSourceError = AddNotebookSourceErrors[keyof AddNotebookSourceErrors];

export type AddNotebookSourceResponses = {
    /**
     * Source added
     */
    201: {
        source?: NotebookSource;
    };
};

export type AddNotebookSourceResponse = AddNotebookSourceResponses[keyof AddNotebookSourceResponses];

export type ListProvidersData = {
    body?: never;
    path?: never;
    query?: {
        guest?: 'true';
    };
    url: '/agent/providers';
};

export type ListProvidersResponses = {
    /**
     * Provider list
     */
    200: {
        providers?: Array<Provider>;
        isGuest?: boolean;
    };
};

export type ListProvidersResponse = ListProvidersResponses[keyof ListProvidersResponses];

export type AddProviderData = {
    body: {
        type: string;
        config: {
            [key: string]: unknown;
        };
    };
    path?: never;
    query?: never;
    url: '/agent/providers';
};

export type AddProviderResponses = {
    /**
     * Created provider
     */
    200: {
        provider?: Provider;
    };
};

export type AddProviderResponse = AddProviderResponses[keyof AddProviderResponses];

export type DeleteProviderData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/agent/providers/{id}';
};

export type DeleteProviderResponses = {
    /**
     * Deleted
     */
    200: {
        message?: string;
    };
};

export type DeleteProviderResponse = DeleteProviderResponses[keyof DeleteProviderResponses];

export type UpdateProviderData = {
    body: {
        config?: {
            [key: string]: unknown;
        };
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/agent/providers/{id}';
};

export type UpdateProviderResponses = {
    /**
     * Updated provider
     */
    200: {
        provider?: Provider;
    };
};

export type UpdateProviderResponse = UpdateProviderResponses[keyof UpdateProviderResponses];

export type DeleteProviderModelData = {
    body: {
        key: string;
        type: 'chat';
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/agent/providers/{id}/models';
};

export type DeleteProviderModelResponses = {
    /**
     * Model removed
     */
    200: {
        message?: string;
    };
};

export type DeleteProviderModelResponse = DeleteProviderModelResponses[keyof DeleteProviderModelResponses];

export type AddProviderModelData = {
    body: {
        key: string;
        name?: string;
        type: 'chat';
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/agent/providers/{id}/models';
};

export type AddProviderModelResponses = {
    /**
     * Model added
     */
    200: {
        message?: string;
    };
};

export type AddProviderModelResponse = AddProviderModelResponses[keyof AddProviderModelResponses];

export type ScrapeGetData = {
    body?: never;
    path?: never;
    query: {
        url: string;
        blockImages?: boolean;
        bypassCaptcha?: boolean;
        timeout?: number;
        format?: 'html' | 'json';
    };
    url: '/scraper';
};

export type ScrapeGetResponses = {
    /**
     * Scraped content
     */
    200: {
        [key: string]: unknown;
    };
};

export type ScrapeGetResponse = ScrapeGetResponses[keyof ScrapeGetResponses];

export type ScrapePostData = {
    body: {
        url: string;
        blockImages?: boolean;
        bypassCaptcha?: boolean;
        timeout?: number;
        format?: 'html' | 'json';
    };
    path?: never;
    query?: never;
    url: '/scraper';
};

export type ScrapePostResponses = {
    /**
     * Scraped content
     */
    200: {
        [key: string]: unknown;
    };
};

export type ScrapePostResponse = ScrapePostResponses[keyof ScrapePostResponses];

export type ListSearchEnginesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/search/engines';
};

export type ListSearchEnginesResponses = {
    /**
     * Engines grouped by category
     */
    200: {
        engines?: {
            [key: string]: Array<{
                name?: string;
                categories?: Array<string>;
            }>;
        };
    };
};

export type ListSearchEnginesResponse = ListSearchEnginesResponses[keyof ListSearchEnginesResponses];

export type GetEngineStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/search/engines/status';
};

export type GetEngineStatusResponses = {
    /**
     * Enabled engines
     */
    200: {
        enabledEngines?: Array<string>;
    };
};

export type GetEngineStatusResponse = GetEngineStatusResponses[keyof GetEngineStatusResponses];

export type UpdateEngineStatusData = {
    body: {
        enabledEngines: Array<string>;
    };
    path?: never;
    query?: never;
    url: '/search/engines/status';
};

export type UpdateEngineStatusResponses = {
    /**
     * Updated
     */
    200: {
        message?: string;
    };
};

export type UpdateEngineStatusResponse = UpdateEngineStatusResponses[keyof UpdateEngineStatusResponses];

export type TestSearchEnginesData = {
    body: {
        engines: Array<string>;
    };
    path?: never;
    query?: never;
    url: '/search/engines/test';
};

export type TestSearchEnginesResponses = {
    /**
     * Test results per engine
     */
    200: {
        results?: {
            [key: string]: {
                working?: boolean;
                error?: string;
            };
        };
    };
};

export type TestSearchEnginesResponse = TestSearchEnginesResponses[keyof TestSearchEnginesResponses];

export type DeleteUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user';
};

export type DeleteUserErrors = {
    /**
     * Authentication required
     */
    401: ErrorResponse;
};

export type DeleteUserError = DeleteUserErrors[keyof DeleteUserErrors];

export type DeleteUserResponses = {
    /**
     * Deleted
     */
    200: {
        message?: string;
    };
};

export type DeleteUserResponse = DeleteUserResponses[keyof DeleteUserResponses];

export type GetUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user';
};

export type GetUserErrors = {
    /**
     * Authentication required
     */
    401: ErrorResponse;
};

export type GetUserError = GetUserErrors[keyof GetUserErrors];

export type GetUserResponses = {
    /**
     * User profile
     */
    200: UserProfile;
};

export type GetUserResponse = GetUserResponses[keyof GetUserResponses];

export type UpdateUserData = {
    body: {
        name?: string;
        email?: string;
        image?: string;
        regenerateApiKey?: boolean;
    };
    path?: never;
    query?: never;
    url: '/user';
};

export type UpdateUserErrors = {
    /**
     * Authentication required
     */
    401: ErrorResponse;
};

export type UpdateUserError = UpdateUserErrors[keyof UpdateUserErrors];

export type UpdateUserResponses = {
    /**
     * Updated
     */
    200: {
        message?: string;
    };
};

export type UpdateUserResponse = UpdateUserResponses[keyof UpdateUserResponses];

export type DeleteUserAccountData = {
    body: {
        accountId: string;
    };
    path?: never;
    query?: never;
    url: '/user/accounts';
};

export type DeleteUserAccountErrors = {
    /**
     * Bad request
     */
    400: ErrorResponse;
    /**
     * Authentication required
     */
    401: ErrorResponse;
};

export type DeleteUserAccountError = DeleteUserAccountErrors[keyof DeleteUserAccountErrors];

export type DeleteUserAccountResponses = {
    /**
     * Unlinked
     */
    200: {
        success?: boolean;
    };
};

export type DeleteUserAccountResponse = DeleteUserAccountResponses[keyof DeleteUserAccountResponses];

export type ListUserAccountsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user/accounts';
};

export type ListUserAccountsErrors = {
    /**
     * Authentication required
     */
    401: ErrorResponse;
};

export type ListUserAccountsError = ListUserAccountsErrors[keyof ListUserAccountsErrors];

export type ListUserAccountsResponses = {
    /**
     * Accounts
     */
    200: Array<{
        id?: string;
        providerId?: string;
        accountId?: string;
        createdAt?: string;
    }>;
};

export type ListUserAccountsResponse = ListUserAccountsResponses[keyof ListUserAccountsResponses];

export type ChangePasswordData = {
    body: {
        currentPassword: string;
        newPassword: string;
    };
    path?: never;
    query?: never;
    url: '/user/password';
};

export type ChangePasswordErrors = {
    /**
     * Authentication required
     */
    401: ErrorResponse;
};

export type ChangePasswordError = ChangePasswordErrors[keyof ChangePasswordErrors];

export type ChangePasswordResponses = {
    /**
     * Changed
     */
    200: {
        message?: string;
    };
};

export type ChangePasswordResponse = ChangePasswordResponses[keyof ChangePasswordResponses];

export type RevokeOtherSessionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user/sessions';
};

export type RevokeOtherSessionsErrors = {
    /**
     * Authentication required
     */
    401: ErrorResponse;
};

export type RevokeOtherSessionsError = RevokeOtherSessionsErrors[keyof RevokeOtherSessionsErrors];

export type RevokeOtherSessionsResponses = {
    /**
     * Revoked
     */
    200: {
        message?: string;
    };
};

export type RevokeOtherSessionsResponse = RevokeOtherSessionsResponses[keyof RevokeOtherSessionsResponses];

export type ListSessionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user/sessions';
};

export type ListSessionsErrors = {
    /**
     * Authentication required
     */
    401: ErrorResponse;
};

export type ListSessionsError = ListSessionsErrors[keyof ListSessionsErrors];

export type ListSessionsResponses = {
    /**
     * Sessions
     */
    200: Array<UserSession>;
};

export type ListSessionsResponse = ListSessionsResponses[keyof ListSessionsResponses];

export type RevokeSessionData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/user/sessions/{id}';
};

export type RevokeSessionErrors = {
    /**
     * Authentication required
     */
    401: ErrorResponse;
};

export type RevokeSessionError = RevokeSessionErrors[keyof RevokeSessionErrors];

export type RevokeSessionResponses = {
    /**
     * Revoked
     */
    200: {
        message?: string;
    };
};

export type RevokeSessionResponse = RevokeSessionResponses[keyof RevokeSessionResponses];

export type GetUserStorageData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user/storage';
};

export type GetUserStorageErrors = {
    /**
     * Authentication required
     */
    401: ErrorResponse;
};

export type GetUserStorageError = GetUserStorageErrors[keyof GetUserStorageErrors];

export type GetUserStorageResponses = {
    /**
     * Storage info
     */
    200: StorageInfo;
};

export type GetUserStorageResponse = GetUserStorageResponses[keyof GetUserStorageResponses];
