/**
 * TradingAgents TypeScript Implementation
 * Core type definitions for the multi-agent trading system
 */

export interface Message {
  role: 'system' | 'user' | 'assistant'
  content: string
  timestamp?: Date
}

export interface InvestDebateState {
  /** Bullish conversation history */
  bullHistory: string
  /** Bearish conversation history */
  bearHistory: string
  /** Full conversation history */
  history: string
  /** Latest response from debaters */
  currentResponse: string
  /** Final judge decision */
  judgeDecision: string
  /** Length of the current conversation */
  count: number
}

export interface RiskDebateState {
  /** Risky agent's conversation history */
  riskyHistory: string
  /** Safe agent's conversation history */
  safeHistory: string
  /** Neutral agent's conversation history */
  neutralHistory: string
  /** Full conversation history */
  history: string
  /** Analyst that spoke last */
  latestSpeaker: string
  /** Latest response by the risky analyst */
  currentRiskyResponse: string
  /** Latest response by the safe analyst */
  currentSafeResponse: string
  /** Latest response by the neutral analyst */
  currentNeutralResponse: string
  /** Judge's decision */
  judgeDecision: string
  /** Length of the current conversation */
  count: number
}

export interface AgentState {
  /** Company that we are interested in trading */
  companyOfInterest: string
  /** Date we are trading at */
  tradeDate: string
  /** Messages exchanged between agents */
  messages: Message[]
  /** Agent that sent the last message */
  sender: string

  // Research reports
  /** Report from the Market Analyst */
  marketReport: string
  /** Report from the Social Media Analyst */
  sentimentReport: string
  /** Report from the News Researcher */
  newsReport: string
  /** Report from the Fundamentals Researcher */
  fundamentalsReport: string

  // Debate states
  /** Current state of the debate on whether to invest */
  investmentDebateState: InvestDebateState
  /** Plan generated by the investment debate */
  investmentPlan: string

  /** Plan generated by the Trader */
  traderInvestmentPlan: string

  /** Current state of the risk debate */
  riskDebateState: RiskDebateState
  /** Risk-adjusted plan after risk team debate */
  finalRiskAdjustedPlan?: string
  /** Fund manager's final decision */
  fundManagerDecision?: string
  /** Final approval status (APPROVE/REJECT/MODIFY) */
  finalApproval?: string
  /** Approved position size */
  approvedPositionSize?: string | null
  /** Final decision made by the Risk Analysts */
  finalTradeDecision: string
}

export interface StructuredReport {
  /** Summary of key points */
  summary: string
  /** Detailed findings */
  findings: string[]
  /** Recommendations */
  recommendations: string[]
  /** Confidence level */
  confidence?: 'High' | 'Medium' | 'Low'
  /** Supporting data */
  data?: Record<string, any>
}

export interface TradingConfig {
  /** LLM provider (openai, anthropic, groq, etc.) */
  llmProvider: 'openai' | 'anthropic' | 'groq' | string
  /** Model for deep thinking tasks */
  deepThinkLLM: string
  /** Model for quick thinking tasks */
  quickThinkLLM: string
  /** Temperature for LLM calls */
  temperature?: number
  /** Base URL for API calls */
  baseUrl?: string
  /** Project directory for data storage */
  projectDir?: string
  /** API keys */
  apiKeys?: {
    openai?: string
    anthropic?: string
    groq?: string
    alphaVantage?: string
    [key: string]: string | undefined
  }
}

export interface StockData {
  date: string
  open: number
  high: number
  low: number
  close: number
  volume: number
  [key: string]: number | string
}

export interface TechnicalIndicators {
  sma50?: number[]
  sma200?: number[]
  ema10?: number[]
  rsi?: number[]
  macd?: number[]
  macdSignal?: number[]
  macdHistogram?: number[]
  bollingerUpper?: number[]
  bollingerMiddle?: number[]
  bollingerLower?: number[]
  atr?: number[]
  vwma?: number[]
  [key: string]: number[] | undefined
}

export interface FundamentalsData {
  marketCap?: number
  peRatio?: number
  dividendYield?: number
  eps?: number
  revenue?: number
  profitMargin?: number
  [key: string]: number | string | undefined
}

export interface NewsItem {
  title: string
  summary: string
  source: string
  url: string
  publishedAt: string
  sentiment?: 'positive' | 'negative' | 'neutral'
}

export interface TradeSignal {
  action: 'BUY' | 'SELL' | 'HOLD'
  confidence: number
  reasoning: string
  timestamp: Date
}

export interface Memory {
  situation: string
  decision: string
  outcome: number
  recommendation: string
  timestamp: Date
}

export type AnalystType = 'market' | 'social' | 'news' | 'fundamentals'
