// This file is generated by api2client. It replaces the bundled Hey API
// client so every request is sent by grab (grab.js.org).

import { createClient as createGrabClient } from "api2client";

import type { Client, Config } from "./types.gen";

export const createClient = (config: Config = {}): Client =>
  createGrabClient(config as never) as unknown as Client;
