name = "research-agent"
compatibility_date = "2024-06-08"
compatibility_flags = ["nodejs_compat"]
main = ".svelte-kit/cloudflare/_worker.js"
site.bucket = "./.cloudflare/public"

[[d1_databases]]
binding = "DB"
database_name = "qwksearch-db"
database_id = "9f45c816-5b19-43e0-8e4e-9edbd6c115b0"

[observability.logs]
enabled = true

[vars]
PUBLIC_DOMAIN  =
PUBLIC_GOOGLE_CLIENT_ID =
GROQ_API_KEY =
STRIPE_API_KEY =
STRIPE_WEBHOOK_SECRET =
XAI_API_KEY =
AUTH_SECRET =
AUTH_RESEND_KEY =
AUTH_GOOGLE_ID =
AUTH_GOOGLE_SECRET =
AUTH_MICROSOFT_ENTRA_ID_ID =
AUTH_MICROSOFT_ENTRA_ID_SECRET =
AUTH_MICROSOFT_ENTRA_ID_ISSUER =
AUTH_FACEBOOK_ID =
AUTH_FACEBOOK_SECRET =
AUTH_DISCORD_ID =
AUTH_DISCORD_SECRET =
AUTH_LINKEDIN_ID =
AUTH_LINKEDIN_SECRET =
AUTH_GITHUB_ID =
AUTH_GITHUB_SECRET =