

/**
 * Retrieves language information for a given IP address using 
 * a remote API. Rate limit 45 req/min
 *
 * You should first use Accept-Language header or navigator.language 
 * in front-end for user-set language
 * https://stackoverflow.com/questions/673905/how-can-i-determine-a-users-locale-within-the-browser/31135571#31135571
 * @param {string} ip - The IP address to look up.
 * @returns {Promise<Object|undefined>} A promise that resolves to an object containing country and language information, or undefined if not found.
 * @returns {string} returns.country - The name of the country.
 * @returns {string} returns.code - The two-letter country code.
 * @returns {string} returns.lang - The two-letter language code.
 * @returns {string} returns.language - The full name of the language.
 * @returns {string} returns.greeting - A greeting in the detected language.
 * @author [ai-research-agent (2024)](https://airesearch.js.org)
 */
export async function getLanguageFromIPRemoteAPI(ip) {

  var url = `http://ip-api.com/line/${ip}?fields=countryCode`;
  var countryCode = (await (await fetch(url)).text())?.toLowerCase().trim();

  if(!countryCode) return;
  //find that coe in countryToLanguage
  const countryInfo = countryToLanguage.find(({code}) => code == countryCode); 

  countryInfo.language = languageNames[countryInfo.lang];
  countryInfo.greeting = translateHello[countryInfo.lang];
  return countryInfo;

}


// 240 countries and which of the 40 major languages is spoken for each
export const countryToLanguage = [
  { country: "Andorra", code: "ad", lang: "es" },
  { country: "United Arab Emirates", code: "ae", lang: "ar" },
  { country: "Afghanistan", code: "af", lang: "fa" },
  { country: "Antigua & Barbuda", code: "ag", lang: "en" },
  { country: "Anguilla", code: "ai", lang: "en" },
  { country: "Albania", code: "al", lang: "ru" },
  { country: "Armenia", code: "am", lang: "ru" },
  { country: "Angola", code: "ao", lang: "pt" },
  { country: "Asia Pacific", code: "ap", lang: "en" },
  { country: "Antarctica", code: "aq", lang: "en" },
  { country: "Argentina", code: "ar", lang: "es" },
  { country: "American Samoa", code: "as", lang: "en" },
  { country: "Austria", code: "at", lang: "de" },
  { country: "Australia", code: "au", lang: "en" },
  { country: "Aruba", code: "aw", lang: "nl" },
  { country: "Aland Islands", code: "ax", lang: "sv" },
  { country: "Azerbaijan", code: "az", lang: "tr" },
  { country: "Bosnia and Herzegovina", code: "ba", lang: "bs" },
  { country: "Barbados", code: "bb", lang: "en" },
  { country: "Bangladesh", code: "bd", lang: "bn" },
  { country: "Belgium", code: "be", lang: "nl" },
  { country: "Burkina Faso", code: "bf", lang: "fr" },
  { country: "Bulgaria", code: "bg", lang: "bg" },
  { country: "Bahrain", code: "bh", lang: "ar" },
  { country: "Burundi", code: "bi", lang: "fr" },
  { country: "Benin", code: "bj", lang: "fr" },
  { country: "Saint Barthelemy", code: "bl", lang: "fr" },
  { country: "Bermuda", code: "bm", lang: "en" },
  { country: "Brunei", code: "bn", lang: "ms" },
  { country: "Bolivia", code: "bo", lang: "es" },
  { country: "Bonaire", code: "bq", lang: "nl" },
  { country: "Brazil", code: "br", lang: "pt" },
  { country: "Bahamas", code: "bs", lang: "en" },
  { country: "Bhutan", code: "bt", lang: "en" },
  { country: "Botswana", code: "bw", lang: "en" },
  { country: "Belarus", code: "by", lang: "ru" },
  { country: "Belize", code: "bz", lang: "en" },
  { country: "Canada", code: "ca", lang: "en" },
  { country: "Congo (DRC)", code: "cd", lang: "fr" },
  { country: "Central African Republic", code: "cf", lang: "fr" },
  { country: "Congo (Brazzaville)", code: "cg", lang: "fr" },
  { country: "Switzerland", code: "ch", lang: "de" },
  { country: "Cote d'Ivoire", code: "ci", lang: "fr" },
  { country: "Cook Islands", code: "ck", lang: "en" },
  { country: "Chile", code: "cl", lang: "es" },
  { country: "Cameroon", code: "cm", lang: "fr" },
  { country: "China", code: "cn", lang: "zh" },
  { country: "Colombia", code: "co", lang: "es" },
  { country: "Costa Rica", code: "cr", lang: "es" },
  { country: "Cuba", code: "cu", lang: "es" },
  { country: "Cabo Verde", code: "cv", lang: "pt" },
  { country: "Curacao", code: "cw", lang: "nl" },
  { country: "Cyprus", code: "cy", lang: "el" },
  { country: "Czech Republic", code: "cz", lang: "cs" },
  { country: "Germany", code: "de", lang: "de" },
  { country: "Djibouti", code: "dj", lang: "fr" },
  { country: "Denmark", code: "dk", lang: "da" },
  { country: "Dominica", code: "dm", lang: "en" },
  { country: "Dominican Republic", code: "do", lang: "es" },
  { country: "Algeria", code: "dz", lang: "ar" },
  { country: "Ecuador", code: "ec", lang: "es" },
  { country: "Estonia", code: "ee", lang: "et" },
  { country: "Egypt", code: "eg", lang: "ar" },
  { country: "Eritrea", code: "er", lang: "ar" },
  { country: "Spain", code: "es", lang: "es" },
  { country: "Ethiopia", code: "et", lang: "ar" },
  { country: "European Union", code: "eu", lang: "en" },
  { country: "Finland", code: "fi", lang: "fi" },
  { country: "Fiji", code: "fj", lang: "en" },
  { country: "Falkland Islands", code: "fk", lang: "en" },
  { country: "Micronesia", code: "fm", lang: "en" },
  { country: "Faroe Islands", code: "fo", lang: "da" },
  { country: "France", code: "fr", lang: "fr" },
  { country: "Gabon", code: "ga", lang: "fr" },
  { country: "United Kingdom", code: "gb", lang: "en" },
  { country: "Grenada", code: "gd", lang: "en" },
  { country: "Georgia", code: "ge", lang: "ru" },
  { country: "French Guiana", code: "gf", lang: "fr" },
  { country: "Guernsey", code: "gg", lang: "en" },
  { country: "Ghana", code: "gh", lang: "en" },
  { country: "Gibraltar", code: "gi", lang: "en" },
  { country: "Greenland", code: "gl", lang: "en" },
  { country: "Gambia", code: "gm", lang: "en" },
  { country: "Guinea", code: "gn", lang: "fr" },
  { country: "Guadeloupe", code: "gp", lang: "fr" },
  { country: "Equatorial Guinea", code: "gq", lang: "es" },
  { country: "Greece", code: "gr", lang: "el" },
  { country: "Guatemala", code: "gt", lang: "es" },
  { country: "Guam", code: "gu", lang: "en" },
  { country: "Guinea-Bissau", code: "gw", lang: "pt" },
  { country: "Guyana", code: "gy", lang: "en" },
  { country: "Hong Kong", code: "hk", lang: "zh" },
  { country: "Honduras", code: "hn", lang: "es" },
  { country: "Croatia", code: "hr", lang: "de" },
  { country: "Haiti", code: "ht", lang: "fr" },
  { country: "Hungary", code: "hu", lang: "hu" },
  { country: "Indonesia", code: "id", lang: "id" },
  { country: "Ireland", code: "ie", lang: "en" },
  { country: "Israel", code: "il", lang: "he" },
  { country: "Isle of Man", code: "im", lang: "en" },
  { country: "India", code: "in", lang: "hi" },
  { country: "British Indian Ocean", code: "io", lang: "en" },
  { country: "Iraq", code: "iq", lang: "ar" },
  { country: "Iran", code: "ir", lang: "fa" },
  { country: "Iceland", code: "is", lang: "is" },
  { country: "Italy", code: "it", lang: "it" },
  { country: "Jersey", code: "je", lang: "en" },
  { country: "Jamaica", code: "jm", lang: "en" },
  { country: "Jordan", code: "jo", lang: "ar" },
  { country: "Japan", code: "jp", lang: "ja" },
  { country: "Kenya", code: "ke", lang: "en" },
  { country: "Kyrgyzstan", code: "kg", lang: "ru" },
  { country: "Cambodia", code: "kh", lang: "ru" },
  { country: "Kiribati", code: "ki", lang: "en" },
  { country: "Comoros", code: "km", lang: "ar" },
  { country: "Saint Kitts & Nevis", code: "kn", lang: "en" },
  { country: "North Korea", code: "kp", lang: "ko" },
  { country: "South Korea", code: "kr", lang: "ko" },
  { country: "Kuwait", code: "kw", lang: "ar" },
  { country: "Cayman Islands", code: "ky", lang: "en" },
  { country: "Kazakhstan", code: "kz", lang: "ru" },
  { country: "Laos", code: "la", lang: "fr" },
  { country: "Lebanon", code: "lb", lang: "ar" },
  { country: "Saint Lucia", code: "lc", lang: "en" },
  { country: "Liechtenstein", code: "li", lang: "de" },
  { country: "Sri Lanka", code: "lk", lang: "en" },
  { country: "Liberia", code: "lr", lang: "en" },
  { country: "Lesotho", code: "ls", lang: "en" },
  { country: "Lithuania", code: "lt", lang: "lt" },
  { country: "Luxembourg", code: "lu", lang: "fr" },
  { country: "Latvia", code: "lv", lang: "lv" },
  { country: "Libya", code: "ly", lang: "ar" },
  { country: "Morocco", code: "ma", lang: "ar" },
  { country: "Monaco", code: "mc", lang: "fr" },
  { country: "Moldova", code: "md", lang: "ro" },
  { country: "Montenegro", code: "me", lang: "sr" },
  { country: "Saint Martin", code: "mf", lang: "fr" },
  { country: "Madagascar", code: "mg", lang: "fr" },
  { country: "Marshall Islands", code: "mh", lang: "en" },
  { country: "North Macedonia", code: "mk", lang: "bg" },
  { country: "Mali", code: "ml", lang: "fr" },
  { country: "Myanmar", code: "mm", lang: "en" },
  { country: "Mongolia", code: "mn", lang: "ru" },
  { country: "Macau", code: "mo", lang: "zh" },
  { country: "Northern Mariana Islands", code: "mp", lang: "en" },
  { country: "Martinique", code: "mq", lang: "fr" },
  { country: "Mauritania", code: "mr", lang: "ar" },
  { country: "Montserrat", code: "ms", lang: "en" },
  { country: "Malta", code: "mt", lang: "en" },
  { country: "Mauritius", code: "mu", lang: "en" },
  { country: "Maldives", code: "mv", lang: "en" },
  { country: "Malawi", code: "mw", lang: "en" },
  { country: "Mexico", code: "mx", lang: "es" },
  { country: "Malaysia", code: "my", lang: "ms" },
  { country: "Mozambique", code: "mz", lang: "pt" },
  { country: "Namibia", code: "na", lang: "en" },
  { country: "New Caledonia", code: "nc", lang: "fr" },
  { country: "Niger", code: "ne", lang: "fr" },
  { country: "Norfolk Island", code: "nf", lang: "en" },
  { country: "Nigeria", code: "ng", lang: "en" },
  { country: "Nicaragua", code: "ni", lang: "es" },
  { country: "Netherlands", code: "nl", lang: "nl" },
  { country: "Norway", code: "no", lang: "nb" },
  { country: "Nepal", code: "np", lang: "ne" },
  { country: "Nauru", code: "nr", lang: "en" },
  { country: "Niue", code: "nu", lang: "en" },
  { country: "New Zealand", code: "nz", lang: "en" },
  { country: "Oman", code: "om", lang: "ar" },
  { country: "Panama", code: "pa", lang: "es" },
  { country: "Peru", code: "pe", lang: "es" },
  { country: "French Polynesia", code: "pf", lang: "fr" },
  { country: "Papua New Guinea", code: "pg", lang: "en" },
  { country: "Philippines", code: "ph", lang: "en" },
  { country: "Pakistan", code: "pk", lang: "ur" },
  { country: "Poland", code: "pl", lang: "pl" },
  { country: "Saint Pierre & Miquelon", code: "pm", lang: "fr" },
  { country: "Puerto Rico", code: "pr", lang: "es" },
  { country: "Palestine", code: "ps", lang: "ar" },
  { country: "Portugal", code: "pt", lang: "pt" },
  { country: "Palau", code: "pw", lang: "en" },
  { country: "Paraguay", code: "py", lang: "es" },
  { country: "Qatar", code: "qa", lang: "ar" },
  { country: "Reunion", code: "re", lang: "fr" },
  { country: "Romania", code: "ro", lang: "ro" },
  { country: "Serbia", code: "rs", lang: "sr" },
  { country: "Russia", code: "ru", lang: "ru" },
  { country: "Rwanda", code: "rw", lang: "en" },
  { country: "Saudi Arabia", code: "sa", lang: "ar" },
  { country: "Solomon Islands", code: "sb", lang: "en" },
  { country: "Seychelles", code: "sc", lang: "fr" },
  { country: "Sudan", code: "sd", lang: "ar" },
  { country: "Sweden", code: "se", lang: "sv" },
  { country: "Singapore", code: "sg", lang: "en" },
  { country: "Slovenia", code: "si", lang: "sl" },
  { country: "Slovakia", code: "sk", lang: "hu" },
  { country: "Sierra Leone", code: "sl", lang: "en" },
  { country: "San Marino", code: "sm", lang: "it" },
  { country: "Senegal", code: "sn", lang: "fr" },
  { country: "Somalia", code: "so", lang: "ar" },
  { country: "Suriname", code: "sr", lang: "nl" },
  { country: "South Sudan", code: "ss", lang: "en" },
  { country: "Sao Tome & Principe", code: "st", lang: "pt" },
  { country: "El Salvador", code: "sv", lang: "es" },
  { country: "Sint Maarten", code: "sx", lang: "nl" },
  { country: "Syria", code: "sy", lang: "ar" },
  { country: "Eswatini", code: "sz", lang: "en" },
  { country: "Turks & Caicos Islands", code: "tc", lang: "en" },
  { country: "Chad", code: "td", lang: "fr" },
  { country: "Togo", code: "tg", lang: "fr" },
  { country: "Thailand", code: "th", lang: "th" },
  { country: "Tajikistan", code: "tj", lang: "ru" },
  { country: "Tokelau", code: "tk", lang: "en" },
  { country: "Timor-Leste", code: "tl", lang: "pt" },
  { country: "Turkmenistan", code: "tm", lang: "tr" },
  { country: "Tunisia", code: "tn", lang: "ar" },
  { country: "Tonga", code: "to", lang: "en" },
  { country: "Turkey", code: "tr", lang: "tr" },
  { country: "Trinidad and Tobago", code: "tt", lang: "en" },
  { country: "Tuvalu", code: "tv", lang: "en" },
  { country: "Taiwan", code: "tw", lang: "zh" },
  { country: "Tanzania", code: "tz", lang: "en" },
  { country: "Ukraine", code: "ua", lang: "ru" },
  { country: "Uganda", code: "ug", lang: "en" },
  { country: "United States", code: "us", lang: "en" },
  { country: "Uruguay", code: "uy", lang: "es" },
  { country: "Uzbekistan", code: "uz", lang: "ru" },
  { country: "Vatican City", code: "va", lang: "it" },
  { country: "St. Vincent", code: "vc", lang: "en" },
  { country: "Venezuela", code: "ve", lang: "es" },
  { country: "British Virgin Islands", code: "vg", lang: "en" },
  { country: "U.S. Virgin Islands", code: "vi", lang: "en" },
  { country: "Vietnam", code: "vn", lang: "vi" },
  { country: "Vanuatu", code: "vu", lang: "en" },
  { country: "Wallis and Futuna", code: "wf", lang: "fr" },
  { country: "Samoa", code: "ws", lang: "en" },
  { country: "Yemen", code: "ye", lang: "ar" },
  { country: "Mayotte", code: "yt", lang: "fr" },
  { country: "South Africa", code: "za", lang: "en" },
  { country: "Zambia", code: "zm", lang: "en" },
  { country: "Zimbabwe", code: "zw", lang: "en" },
  { country: "Unknown", code: "zz", lang: "en" },
];

//40 major languages names in English and codes 
const languageNames = {
    ar: "Arabic",
    bg: "Bulgarian",
    bn: "Bengali",
    bs: "Bosnian",
    cs: "Czech",
    da: "Danish",
    de: "German",
    el: "Greek",
    en: "English",
    es: "Spanish",
    et: "Estonian",
    fa: "Persian",
    fi: "Finnish",
    fr: "French",
    he: "Hebrew",
    hi: "Hindi",
    hu: "Hungarian",
    id: "Indonesian",
    is: "Icelandic",
    it: "Italian",
    ja: "Japanese",
    ko: "Korean",
    lt: "Lithuanian",
    lv: "Latvian",
    ms: "Malay",
    nb: "Norwegian",
    ne: "Nepali",
    nl: "Dutch",
    pl: "Polish",
    pt: "Portuguese",
    ro: "Romanian",
    ru: "Russian",
    sl: "Slovenian",
    sr: "Serbian",
    sv: "Swedish",
    th: "Thai",
    tr: "Turkish",
    ur: "Urdu",
    vi: "Vietnamese",
    zh: "Chinese"
};

const translateHello = {
  ar: "مرحبا (Marhaban)",
  bg: "Здравейте (Zdraveyte)",
  bn: "হ্যালো (Hyālō)",
  bs: "Zdravo",
  cs: "Ahoj",
  da: "Hej",
  de: "Hallo",
  el: "Γεια σας (Geia sas)",
  en: "Hello",
  es: "Hola",
  et: "Tere",
  fa: "سلام (Salaam)",
  fi: "Hei",
  fr: "Bonjour",
  he: "שלום (Shalom)",
  hi: "नमस्ते (Namaste)",
  hr: "Bok",
  hu: "Szia",
  id: "Halo",
  is: "Halló",
  it: "Ciao",
  ja: "こんにちは (Konnichiwa)",
  ka: "გამარჯობა (Gamarjoba)",
  ko: "안녕하세요 (Annyeong haseyo)",
  lo: "ສະບາຍດີ (Sabaidee)",
  lt: "Labas",
  lv: "Sveiki",
  ms: "Hello",
  my: "မင်္ဂလာပါ (Mingalarba)",
  nb: "Hei",
  ne: "नमस्ते (Namaste)",
  nl: "Hallo",
  pl: "Cześć",
  pt: "Olá",
  ro: "Salut",
  ru: "Здравствуйте (Zdravstvuyte)",
  sk: "Ahoj",
  sl: "Zdravo",
  sr: "Здраво (Zdravo)",
  sv: "Hej",
  tg: "Салом (Salom)",
  th: "สวัสดี (Sawasdee)",
  tk: "Salam",
  to: "Mālō e lelei",
  tr: "Merhaba",
  uk: "Привіт (Pryvit)",
  ur: "ہیلو (Hello)",
  uz: "Salom",
  vi: "Xin chào",
  zh: "你好 (Nǐ hǎo)",
};
