services:
  - type: web
    name: scraper
    env: docker
    plan: free
    region: oregon
    branch: master
    rootDir: packages/scraper/
    autoDeploy: true
    healthCheckPath: /
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000