[project]
name = "tinygrad-mnist-example"
version = "0.1.0"
description = "Complete tinygrad MNIST training example with visualization"
authors = [
    { name = "User", email = "user@example.com" }
]
dependencies = [
    "tinygrad>=0.10.0",
    "numpy>=1.21.0",
    "matplotlib>=3.5.0",
]
requires-python = ">=3.8"

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
    "black>=22.0.0",
    "flake8>=4.0.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
dev-dependencies = []
