openapi: 3.0.3
info:
  title: QwkSearch API
  description: Search and outline a topic base with AI Research Agent
  version: 0.9.8
paths:
  /api/search:
    get:
      summary: Search the web
      description: Retrieves web search results based on the query.
      parameters:
        - name: q
          in: query
          description: Search query string
          required: true
          schema:
            type: string
        - name: cat
          in: query
          description: Category of search (optional)
          required: false
          schema:
            type: integer
            default: 0
        - name: time
          in: query
          description: Recency filter (optional)
          required: false
          schema:
            type: integer
            default: 0
        - name: public
          in: query
          description: Use public SearXNG instances (optional)
          required: false
          schema:
            type: boolean
            default: false
        - name: limitExtract
          in: query
          description: Max number of top results to extract (optional)
          required: false
          schema:
            type: integer
            default: 4
        - name: page
          in: query
          description: Pagination for results (optional)
          required: false
          schema:
            type: integer
            default: 1
      responses:
        '200':
          description: A list of search results
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: array
                    items:
                      type: object
                      properties:
                        title:
                          type: string
                          description: Title of the search result 
                          example: "QwkSearch - Search and outline a topic base with AI Research Agent"
                        link:
                          type: string
                          description: URL of the search result
                          example: "https://qwksearch.com"
                        snippet:
                          type: string
                          description: Snippet of the search result
                          example: "QwkSearch is a search engine that allows you to..."
                  elapsedTime:
                    type: integer
                    description: Time taken for the search (in ms)
        '400':
          description: Missing required query parameter `q`
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Server error when fetching search results
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /api/extract:
    get:
      summary: Extract main content and cite from any URL
      description: Extracts content (either full HTML or summary) from a given URL using `extract` or `scrapeURL`.
      parameters:
        - name: url
          in: query
          description: URL to extract content from
          required: true
          schema:
            type: string
        - name: full
          in: query
          description: Return full HTML content if set to true (optional)
          required: false
          schema:
            type: boolean
            default: false
      responses:
        '200':
          description: Extracted content or HTML
          content:
            application/json:
              schema:
                type: object
                properties:
                  html:
                    type: string
                    description: Full HTML of the page (if `full` is true)
                  title:
                    type: string
                    description: Title of the page (if `full` is not provided)
                  content:
                    type: string
                    description: Extracted content summary of the page
        '500':
          description: Server error or missing URL parameter
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string