// import qwksearchSidebar from "./docs/api/sidebar";

let qwksearchSidebar = false;

const sidebarConfig = [
  {
    type: "category",
    label: "API Routes",
    link: {
      type: "generated-index",
      title: "Qwksearch API",
      slug: "/category/qwksearch-api",
    },
    items: qwksearchSidebar ? qwksearchSidebar :  [
      {
        type: "autogenerated",
        dirName: "api",
      },
    ],
  },

  {
    type: "category",
    label: "Files & Functions",
    items: [
      {
        type: "autogenerated",
        dirName: "functions",
      },
    ],
  },

  {
    type: "category",
    label: "Web App Functions",
    items: [
      {
        type: "autogenerated",
        dirName: "web-app",
      },
    ],
  },
];

export default {
  qwksearch: sidebarConfig,
  functions: sidebarConfig,
};
