
import qwksearchSidebar from "./docs/routes/sidebar";

export default {
  qwksearch: [
    {
      type: "category",
      label: "API Routes",
      link: {
        type: "generated-index",
        title: "Qwksearch API",
        slug: "/category/qwksearch-api",
      },
      items: qwksearchSidebar,
    },

    {
      type: "category",
      label: "Files & Functions",
      link: {
        type: "doc",
        id: "intro",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "functions",
        },
      ],
    },  
  ],
  
  functions: [
    {
      type: "category",
      label: "API Routes",
      link: {
        type: "generated-index",
        title: "Qwksearch API",
        slug: "/category/qwksearch-api",
      },
      items: qwksearchSidebar,
    },

    {
      type: "category",
      label: "Files & Functions",
      link: {
        type: "doc",
        id: "intro",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "functions",
        },
      ],
    },  
  ],
};
